### ISSUE TITLE
Conda files are not reproducible due to timestamp in `index.json`.

### ISSUE THREAD

**Issue by gpdaniels** [prefix-dev/pixi-build-backends#36]
I'm trying to start from nothing and create reproducible builds for the entire dependency structure of my project.

Starting from a `gcr.io/distroless/base-debian12` and adding: `sh`, `bash`, `env`, `tr`, `basename`, `diff`, `tail`, `grep`, `sort`, `rm`, `sed` and a bodged together `lld` script (that outputs the version information so I can workaround https://github.com/prefix-dev/pixi/issues/2694 ). **I can `pixi build` my c++ project. 🎉** 

My issue is that the `*.conda` file produced by this process changes with every build, is this expected behaviour?

Extracting out the files I can see that the hashes of the files match, except the `index.json` due to the timestamp field.

Weirdly the `pkg*.zst` files also doesn't match even though the contents are the same, I presume that's some odd  non-deterministic compression issue, is the compression threaded?

Some `sha256sum`s:
```
4ccd6d533c1f48e198be3087574467ea601ef672  ./V1/test-0.0.0-hbf21a9e_0.conda                        <---DIFF
1e1b9de7f0b518ff5101f33ac84d9784c6d376c4  ./V2/test-0.0.0-hbf21a9e_0.conda                        <---DIFF

--

24ab44a0bee2b5ef4d928277ee4320579e421599  ./V1/metadata.json
24ab44a0bee2b5ef4d928277ee4320579e421599  ./V2/metadata.json

--

05c7aa42d49c6d8c16d56cb637d70b1d57f253a0  ./V1/pkg-test-0.0.0-hbf21a9e_0.tar.zst                  <---DIFF
4b33e2bc8dfecadfc6e49c8b8bbfaf78d5a0ed16  ./V2/pkg-test-0.0.0-hbf21a9e_0.tar.zst                  <---DIFF

ca5a3984d7004e9577c973341d197d0f049172b2  ./V1/pkg-test-0.0.0-hbf21a9e_0/bin/test
ca5a3984d7004e9577c973341d197d0f049172b2  ./V2/pkg-test-0.0.0-hbf21a9e_0/bin/test

--

26e42256cc2871155a02e8a8a807017d7bc69651  ./V1/info-test-0.0.0-hbf21a9e_0.tar.zst                 <---DIFF
8dd4656d9f38eb5b813b8e89c506cf0996b68f0d  ./V2/info-test-0.0.0-hbf21a9e_0.tar.zst                 <---DIFF

35745eb170ef8f5fcf8da783e213c353f523588a  ./V1/info-test-0.0.0-hbf21a9e_0/info/paths.json
35745eb170ef8f5fcf8da783e213c353f523588a  ./V2/info-test-0.0.0-hbf21a9e_0/info/paths.json

15fbe1dcad505c3498ae95977deb45914bb63b49  ./V1/info-test-0.0.0-hbf21a9e_0/info/about.json
15fbe1dcad505c3498ae95977deb45914bb63b49  ./V2/info-test-0.0.0-hbf21a9e_0/info/about.json

bf21a9e8fbc5a3846fb05b4fa0859e0917b2202f  ./V1/info-test-0.0.0-hbf21a9e_0/info/hash_input.json
bf21a9e8fbc5a3846fb05b4fa0859e0917b2202f  ./V2/info-test-0.0.0-hbf21a9e_0/info/hash_input.json

5dfe2f605fcff5e9e4fef24365df6fb9d38b39cb  ./V1/info-test-0.0.0-hbf21a9e_0/info/index.json         <---DIFF
c34cb2a796cf555c0be54629408ec27b520d7fae  ./V2/info-test-0.0.0-hbf21a9e_0/info/index.json         <---DIFF

cd0d4cc32346750408f7d4f5e78ec9a6e5b79a0d  ./V1/info-test-0.0.0-hbf21a9e_0/info/tests/tests.yaml
cd0d4cc32346750408f7d4f5e78ec9a6e5b79a0d  ./V2/info-test-0.0.0-hbf21a9e_0/info/tests/tests.yaml

```

Questions:
- Is it possible to override/disable the timestamp during packaging?
    - Either the ability to set it to a known value or a method to zero it out. I've seen in `rattler-build` it overrides the timestamp of a rebuild ( https://github.com/prefix-dev/rattler-build/blob/4078d3a9dc056f928ce56546acad8e9808b7c02f/docs/rebuild.md )
- Any ideas what could be causing the compression inconsistency?

**Comment by wolfv** [comment]
Hi @gpdaniels - that's exciting! 

Our current strategy for reproducible builds is that `rattler-build` stores all input data (including the timestamp) inside the package, and you can run the `rebuild` command to rebuild an existing package.

So if you have a conda package that was built wiht rattler-build somewhere, you can run:

```
rattler-build rebuild -f ./mypkg-...conda
```

And if things go well, it should reproduce!

**Comment by wolfv** [comment]
Now, having said that, we haven't really exposed this to `pixi` / `pixi-build` just yet. Pixi build in general is still a very fresh feature :)

**Comment by gpdaniels** [comment]
Thanks for the information.

So my current best plans of action are either:
- Extract all the files, overwrite the timestamp and repackage them.
- Use a custom version of `rattler-build`, adding the option to zero the timestamp and seeing what I can do about the compression non-determinism.

**Comment by gpdaniels** [comment]
Seems I've found a third way, googling around I found [libfaketime](https://github.com/wolfcw/libfaketime) which can overwrite the system time.

Also handily it's available via pixi.

So I've added:
```
pixi global install libfaketime
export LD_PRELOAD=/root/.pixi/envs/libfaketime/lib/faketime/libfaketime.so.1
export FAKETIME="2020-01-01 00:00:00"
pixi build
```

This gives me identical conda files which I can cache really easily.

**Comment by wolfv** [comment]
Wow that's cool!

**Comment by wolfv** [comment]
Wow that's cool!
